### ISSUE TITLE
Error on example scrape

### ISSUE THREAD

**Issue by JohnMcLear** [nrabinowitz/pjscrape#11] opened 2012-02-28 21:43 UTC
<pre>
* CLIENT: mw.loader::execute> Exception thrown by jquery.ui.mouse: Result of expression '$.widget' [undefined] is not a function. (http://bits.wikimedia.org/en.wikipedia.org/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=20111213T185322Z line 142)
* CLIENT: TypeError: Result of expression '$.widget' [undefined] is not a function. (http://bits.wikimedia.org/en.wikipedia.org/load.php?debug=false&lang=en&modules=jquery.ui.dialog%2Cdraggable%2Cmouse%2Cposition%2Cresizable&skin=vector&version=20110919T161434Z&* line 40)
</pre>

**Comment by nrabinowitz** [comment] 2012-02-28 22:22
Which example does this error occur in?

It looks like the Wikipedia page I was using as an example target has changed, so I'll need to update the examples, but that shouldn't throw an error.

**Comment by JohnMcLear** [comment] 2012-02-28 23:48
<pre>
pjs.addSuite({
    // single URL or array
    url: 'http://en.wikipedia.org/wiki/List_of_towns_in_Vermont',
    // single function or array, evaluated in the client
    scraper: function() {
        return $('h1#firstHeading').text();
    }
});</pre>

**Comment by nrabinowitz** [comment] 2012-02-28 23:58
Hmm. I was able to reproduce, but only once, and on repeated runs the code ran without errors. Even when the errors are thrown, the scrape completes properly, returning data as expected.

At a guess, this is a bad interaction between PhantomJS and `jquery.ui.mouse`, and isn't possible to fix in the Pjscrape code, so I'm going to close the issue.

**Closed as completed by nrabinowitz** 2012-02-28 23:58 UTC

**Comment by stefek99** [comment] 2012-05-15 20:01
Encountered similar error, search for error pointed me here.

phantomjs --version
1.5.0

```
Michals-MacBook-Air-2:pjscrape-tutorial stefanek$ phantomjs ../pjscrape/pjscrape.js my_config.js 
* Suite 0 starting
* Opening http://en.wikipedia.org/wiki/List_of_towns_in_Vermont
* CLIENT: would insert toolbar on this page
* Scraping http://en.wikipedia.org/wiki/List_of_towns_in_Vermont
* CLIENT: mw.loader::execute> Exception thrown by jquery.tablesorter: 'undefined' is not a function
* CLIENT: TypeError: 'undefined' is not a function
* CLIENT: mw.loader::execute> Exception thrown by jquery.ui.mouse: 'undefined' is not a function
* CLIENT: TypeError: 'undefined' is not a function
* Suite 0 complete
* Writing 1 items
["\n\t\t\t\tList of towns in Vermont\n\t\t\t"]
* Saved 1 items
```

This is probably something related with the page itself - it uses sortable UI widgets. It might be nice to run demo without errors though :)

Note: PyPhantomJS has been discontinued so I will probably proceed with core Phantom.
